image: node:18-alpine3.20

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn install
    - yarn build
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

create-pages:
  stage: deploy
  script:
    - yarn install
    - yarn build
    - mv ./build public
  pages:
    path_prefix: "pr-$CI_MERGE_REQUEST_IID" # Results in paths like mr-123
  only:
    - external_pull_requests
